from pathlib import Path
from types import SimpleNamespace

import pytest

import scripts.generate_dependency_locks as lock_generator
from scripts.generate_dependency_locks import (
    deterministic_lock_text,
    validate_compiled_lock,
)


HASH = "a" * 64


def _compiled_body() -> str:
    return f"""# generated by a resolver
alpha==1.2.3 \\
    --hash=sha256:{HASH} \\
    --hash=sha256:{HASH}
beta==4.5.6 \\
    --hash=sha256:{HASH}
"""


def test_compiled_lock_requires_exact_hashed_entries():
    assert validate_compiled_lock(_compiled_body()) == ["alpha", "beta"]

    with pytest.raises(ValueError, match="non-exact"):
        validate_compiled_lock("alpha>=1.2\n")
    with pytest.raises(ValueError, match="no SHA-256"):
        validate_compiled_lock("alpha==1.2.3\n")


def test_deterministic_lock_text_removes_transient_resolver_header(tmp_path):
    input_path = tmp_path / "requirements" / "gen2.in"
    input_path.parent.mkdir()
    input_path.write_text("alpha==1.2.3\n", encoding="utf-8")

    kwargs = {
        "input_path": input_path,
        "repo_root": tmp_path,
        "generator_version": "7.5.0",
        "resolver": "backtracking",
    }
    first = deterministic_lock_text(
        "# generated at 10:00\n" + _compiled_body(), **kwargs
    )
    second = deterministic_lock_text(
        "# generated at 11:00\n" + _compiled_body(), **kwargs
    )

    assert first == second
    assert "# generator: pip-tools==7.5.0" in first
    assert "# input: requirements/gen2.in" in first
    assert "generated at" not in first
    assert first.endswith("\n")


def test_lock_generation_rejects_duplicate_entries():
    duplicate = (
        _compiled_body()
        + "alpha==9.9.9 " + chr(92) + "\n"
        + "    --hash=sha256:" + HASH + "\n"
    )

    with pytest.raises(ValueError, match="Duplicate package"):
        validate_compiled_lock(duplicate)


def test_lock_tool_input_is_pinned_and_separate_from_runtime_inputs():
    path = (
        Path(__file__).resolve().parents[1]
        / "requirements"
        / "inputs"
        / "lock-tools-py312.in"
    )
    lines = [
        line.strip()
        for line in path.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    ]

    assert lines == ["pip-tools==7.5.0"]


def test_generate_lock_is_deterministic_and_creates_nested_output(
    tmp_path, monkeypatch
):
    repo_root = tmp_path / "repo"
    repo_root.mkdir()
    (repo_root / "pyproject.toml").write_text("[project]\\nname='test'\\n")
    input_path = repo_root / "requirements" / "gen2.in"
    input_path.parent.mkdir()
    input_path.write_text("alpha>=1.0\\n", encoding="utf-8")

    def fake_run(command, **_kwargs):
        output_arg = next(
            item for item in command if item.startswith("--output-file=")
        )
        output_path = Path(output_arg.split("=", 1)[1])
        output_path.write_text(_compiled_body(), encoding="utf-8")
        return SimpleNamespace(returncode=0, stdout="", stderr="")

    monkeypatch.setattr(lock_generator, "_pip_tools_version", lambda: "7.5.0")
    monkeypatch.setattr(lock_generator.shutil, "which", lambda _: "fake-pip-compile")
    monkeypatch.setattr(lock_generator.subprocess, "run", fake_run)

    first_path = repo_root / "locks" / "first" / "gen2.txt"
    second_path = repo_root / "locks" / "second" / "gen2.txt"
    first = lock_generator.generate_lock(
        input_path=input_path,
        output_path=first_path,
        repo_root=repo_root,
    )
    second = lock_generator.generate_lock(
        input_path=input_path,
        output_path=second_path,
        repo_root=repo_root,
    )

    assert first.read_text(encoding="utf-8") == second.read_text(encoding="utf-8")
    assert first.read_text(encoding="utf-8").count("--hash=sha256:") == 3
    with pytest.raises(FileExistsError):
        lock_generator.generate_lock(
            input_path=input_path,
            output_path=first_path,
            repo_root=repo_root,
        )
